Compatible with django3 api + GH actions
EBI-Metagenomics/ebi-metagenomics-webkit pull request #42
Opened 2021-04-23 09:36 UTC by gustavo-salazar

This PR contains basically 2 changes:
1. in the `api.js` anytime it reads `someApiResponse.data.id` is changed to `someApiResponse.data && someApiResponse.data.id` because the API now returns `data: null` when is empty instead of `data: {data: null}`
2. Changing from travis to GH actions. Most of the changed files in the PR are basically moving them from `travis/` to `ci/`

*Note 1*: Sorry about all the prettier changes, I tried to control all the noise in the PR by adding a `.prettier` but it's still full of meaningless formatting changes.

*Note 2*: Please squash all the commits of this PR, as most of them are just trials into the GH actions workflow.

2021-04-28 19:50 UTC, caballero requested changes
Changes and additions are ok, however, I noticed some .DS_store files being part of the repo, as this push is moving the test files, could be good to delete those files. Also, there are some sha1 files for the sha1 files (ci/emg_api_datafiles/results/2017/11/ERP104174/version_5.0/ERZ477/006/ERZ477576_FASTA/hashes/ERZ477576_FASTA.fasta.gz.sha1.sha1)

2021-05-05 15:24 UTC, mberacochea commented on README.md
> +[![Codacy Badge](https://api.codacy.com/project/badge/Coverage/5349bdf1c0204b28940d3bf19c894d95)](https://www.codacy.com/app/mb1069/ebi-metagenomics-webkit?utm_source=github.com&utm_medium=referral&u
Codacy is still using Miguel's account, I've createa a ticket to migrate that

2021-05-05 15:42 UTC, mberacochea approved these changes
Thank you Gustavo, it looks OK to me. Only thing is to remove those .DS files.

I'll merge (and squash) this as soon as I can.

**No problem :)**
      Note 1: Sorry about all the prettier changes, I tried to control all the noise in the PR by adding a .prettier but it's still full of meaningless formatting changes.

**Yes, I'll squash and merge this.**
     Note 2: Please squash all the commits of this PR, as most of them are just trials into the GH     actions workflow.

2021-05-07 11:19 UTC, gustavo-salazar commented
I have deleted the files requested by @caballero and also notice the tests were failing because of some changes in the API model; which is now fixed.

2021-05-10 16:19 UTC, merged